apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ${DOCKER_USERNAME}/express:latest
        env:
        - name: DB_USER
          value: postgres
        - name: DB_HOST
          value: "10.152.183.127"  # Esto se actualizará dinámicamente
        - name: DB_NAME
          value: clothing_store
        - name: DB_PASSWORD
          value: postgres
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
