apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-1
  template:
    metadata:
      labels:
        app: db-1
    spec:
      containers:
        - name: db-1
          image: marcocastrof/postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: clothing_store  # Nombre de la base de datos
            - name: POSTGRES_PASSWORD
              value: db-1  # Contraseña del usuario db-1

---
apiVersion: v1
kind: Service
metadata:
  name: db-1-service
spec:
  selector:
    app: db-1
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
